### PR TITLE
Axis label bug patch (Fixes #64)

### LINKED ISSUE #64: Y-axis label not aligning properly during reflow
# Bug Report

## Description

When we create a graph with space as a y-axis label and try to update the y-axis label with reflow, the y-axis label is being displayed near the tick values. I don't see this issue when the y2 axis is present. 

## Steps to Reproduce

1. Create a graph having only y-axis with space as y-axis label
2. Try to update the y-axis label with the reflow method
3. y-axis label is not being displayed at the same position, it has been moved towards tick values.

## Additional Context / Screenshots

I added a screenshot to compare how the label is displaying, For the first graph, I mentioned the y-axis label and for the second graph, i passed space as the y-axis label. After panning, I updated the y-axis label through the reflow method, the y-axis label has moved towards the y-axis ticks.
Screenshot 2021-01-20 at 12 41 28 PM

## Expected Behavior

y-axis label should be aligned properly like how it was before

### PR DESCRIPTION
**Pull request by sdadn**
### Summary

Patched a bug which causes axis labels to not in the appropriate position after reflow if a space was used as the original value.

Closes #64 

### Deployment Link

https://terra-graphs-deployed-pr-69.herokuapp.com/

### Additional Details

Before fix: (width does not update after updating label through reflow)

CleanShot 2021-02-15 at 09 58 27@2x

After fix: (width now updates to have padding around label after reflow)

CleanShot 2021-02-15 at 09 59 21@2x

Thank you for contributing to Terra.
@cerner/terra
@cerner/carbon

### CODE REVIEW

File: packages/carbon-graphs/src/js/controls/Scatter/helpers/helpers.js [hunk 1]
```diff
@@ -134,6 +134,14 @@ const dataPointActionHandler = (value, index, target) => {
...
  */
 const translateScatterGraph = (scale, canvasSVG, config) => {
+  canvasSVG
+    .select(`.${styles.currentPointsGroup}`)
+    .attr(
+      'transform',
+      `translate(${getXAxisXPosition(
+        config,
+      )},${calculateVerticalPadding(config)})`,
+    );
```
Comment (yuderekyu) [inline packages/carbon-graphs/src/js/controls/Scatter/helpers/helpers.js:144]: will abstracting this into its own helper do more harm/good? i'm not super familiar with this code, but i do notice we execute this logic 3 times. the only thing that differs is the style. probably come up with better names for the helper and params

```js
const helper = (style, config) => (
  canvasSVG
    .select(`.${styles}.${style}`)
    .attr(
      'transform',
      `translate(${getXAxisXPosition(config)},${calculateVerticalPadding(config)})`,
    );
);

Comment (sdadn) [reply packages/carbon-graphs/src/js/controls/Scatter/helpers/helpers.js]: That sounds like a good idea, updated here: fc46388c575dc0344b6c92180408c47b8a0c5dc5

**Comment by AshishMotanamGurunadham** [comment]
Have you tested these changes in all browsers?

**Comment by AshishMotanamGurunadham** [comment]
Can you add before and after screenshots in the description?

**Comment by AshishMotanamGurunadham** [comment]
Can you also add some unit test cases like test the position of label and y-axis during initial loadout(when " " is passed as label) and reflow(when data is passed as label), test content container position in this scenario, test the position of label and legend during initial loadout(when " " is passed as label) and reflow(when data is passed as label) etc.

File: packages/carbon-graphs/src/js/helpers/axis.js [hunk 2]
```diff
@@ -1197,7 +1197,6 @@ const calculateAxesLabelSize = (config) => {
   config.axisLabelHeights.x = 0;
   config.axisLabelWidths.y = 0;
   config.axisLabelWidths.y2 = 0;
-  config.axisInfoRowLabelHeight = 0;
```
Comment (AshishMotanamGurunadham) [inline packages/carbon-graphs/src/js/helpers/axis.js:1200]: Can you please explain the reason for this removal?

Comment (sdadn) [reply packages/carbon-graphs/src/js/helpers/axis.js:1200]: This was interfering with the new logic to update the container height to accommodate for x-axis and and axis info row on a bar chart. Removing this resolved the issue and caused all unit tests to pass again.

File: packages/carbon-graphs/src/js/controls/Graph/helpers/helpers.js [hunk 3]
```diff
@@ -925,7 +927,28 @@ const drawNoDataView = (config, svg) => {
...
+/**
+ * Translate a SVG element so it's within the canvas
+ *
+ * @private
+ * @param {d3.selection} canvasSVG - d3 selection node of canvas svg
+ * @param {object} style - element to translate
+ * @param {object} config - config object derived from input JSON
+ * @returns {undefined}
+ */
+const translateSVGElement = (canvasSVG, style, config) => {
```
Comment (mraplumb) [inline packages/carbon-graphs/src/js/controls/Graph/helpers/helpers.js:939]: since we added a new function, we should have some unit tests for it.

File: packages/carbon-graphs/src/js/helpers/axis.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (sdadn) [reply packages/carbon-graphs/src/js/helpers/axis.js:1200]: Yes, this had no affect on the code prior to this change and was interfering with the bug fix.

**Comment by sdadn** [comment]
> Can you add before and after screenshots in the description?

@AshishMotanamGurunadham added screenshots

**Comment by NarasimhaShenoi** [comment]
Hi All, when this can be merged. can you please provide an ETA for the same?

File: packages/carbon-graphs/tests/unit/controls/Graph/GraphPanning-spec.js [hunk 4]
```diff
@@ -92,6 +96,128 @@ describe('Graph - Panning', () => {
...
+        expect(
+          getSVGAnimatedTransformList(
+            fetchElementByClass(styles.axisY2).getAttribute(
+              'transform',
+            ),
+          ).translate[0],
+        ).toBeCloserTo(930);
+        done();
+      });
+    });
```
Comment (AshishMotanamGurunadham) [inline packages/carbon-graphs/tests/unit/controls/Graph/GraphPanning-spec.js:220]: I think we can add three more tests here: 

- check the height of the canvas container when the label is passed for the x-axis during reflow.
- check the position of the legend when label is passed for the x-axis during reflow.
- check the position of the content container when label is passed to the y-axis during reflow.

File: packages/carbon-graphs/src/js/controls/Graph/helpers/helpers.js (hunk 3 above)
Comment (sdadn) [reply packages/carbon-graphs/src/js/controls/Graph/helpers/helpers.js:939]: After discussion, we concluded that it's not possible to unit test this function due to its design as part of Carbon's architecture.

**Comment by joelsamthomas** [comment]
@sdadn  any ETA on this. We are planning to consume this version once this gets released

**Review by mraplumb — APPROVED** [review]

**Review by AshishMotanamGurunadham — APPROVED** [review]
