### PR TITLE
Timeline graph only works if it is the first/only graph on a page

### LINKED ISSUE #84: Timeline graph only works if it is the first/only graph on a page.
# Bug Report

## Description
At two points (lines 206, 210) the Carbon timeline graph uses getElementByClassName on the entire document object to retrieve elements using generic class names shared by all of the graphs. This results in the wrong elements being used for size calculations if other graphs are on the page.

### Graphs affected

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [ ]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [x]  Timeline

## Steps to Reproduce

1. Put a Gantt chart before a Timeline on the same page.
2.
3.
4.

## Link to CodeSandbox
Use [this](https://codesandbox.io/s/keen-thunder-nh5gk?file=/src/data.js) template to reproduce the behavior.

## Expected Behavior
The size calculations are done from attributes of the correct graph.

## Possible Solution
Replace the timeline's logic with the logic used by all the other graphs, using the graphContainer instead of the DOM to handle these calculations. Alternatively, for a quick and dirty fix that leaves the timeline graph with its unique behavior, add an intermediate ID selector using the graph ID passed into the constructor on the initial JSON configuration.
-  e.g. document.getElementById(config.bindTo).getElementsByClassName("tick")

## Environment
Carbon Graphs 2.16.0

### PR DESCRIPTION
**Pull request by AshishMotanamGurunadham**
### Summary

- Timeline graph only works if it is the first/only graph on a page. Changed the way the timeline graph access the ticks to fix this issue.

Closes #84 

### Deployment Link

https://terra-graphs-deployed-pr-#.herokuapp.com/

### Testing

- Wrote test case by reproducing the issue and testing the translate position of timeline graph.

### Before:

image

### After:

image

Thank you for contributing to Terra.
@cerner/terra
@cerner/carbon

### CODE REVIEW

File: packages/carbon-graphs/tests/unit/controls/Timeline/TimelineLoad-spec.js [hunk 1]
```diff
@@ -756,4 +762,33 @@ describe('Timeline - Load', () => {
       ).toEqual(inputPrimary.key);
     });
   });
+  describe('When timeline is created as second graph in page', () => {
+    it('should render graph from right point', () => {
```
Comment (sdadn) [inline packages/carbon-graphs/tests/unit/controls/Timeline/TimelineLoad-spec.js:766]: nit: `should render graph from the right side of the container`

**Review by mraplumb — CHANGES_REQUESTED** [review]

File: packages/carbon-graphs/tests/unit/controls/Timeline/TimelineLoad-spec.js (hunk 1 above)
Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/tests/unit/controls/Timeline/TimelineLoad-spec.js]: It is the correct position, Andy. Fixed [here](https://github.com/cerner/terra-graphs/pull/91/commits/c80f2946bf5a8d9dcb35cff6acf77e7f3cd46d8d#diff-468a3e72133761d3dc61f876f1c9b2a5c228031c41b11906708ce33d186a957bR766).

File: packages/carbon-graphs/CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,9 @@
 
 ## Unreleased
 
+*Changed 
+ * Fixed Timeline graph issue when it is generated as second graph in page.
```
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/CHANGELOG.md]: Fixed [here](https://github.com/cerner/terra-graphs/pull/91/commits/c80f2946bf5a8d9dcb35cff6acf77e7f3cd46d8d#diff-7b73f4b73c95577a16e8a58d2e1377b2204811d315c020884e80b9f22128c42aR6).

File: packages/carbon-graphs/src/js/controls/Timeline/Timeline.js [hunk 3]
```diff
@@ -188,7 +188,7 @@ class Timeline extends Construct {
     const containerSVG = d3
       .select(this.config.bindTo)
       .append('div')
-      .classed(styles.container, true)
+      .classed(styles.timelineContainer, true)
```
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/src/js/controls/Timeline/Timeline.js:191]: I checked for **styles.container** usage in all timeline graph files (including test files)  and changed everywhere accordingly.

[the remark this answers is not in the document]
Comment (mraplumb) [reply packages/carbon-graphs/src/js/controls/Timeline/Timeline.js:191]: I think I am less concerned that you accounted for all the instances in the code that needed to be updated.  My concern was more for things like reflow, or something like it which might touch multiple graphs, that might select graph containers using `styles.container` to do updates where the timeline graphs would no longer qualify for.  

I'm not sure if this situation exists but wanted to make sure we have verified that since consumers often have multiple graphs together on a view.

File: packages/carbon-graphs/CHANGELOG.md [hunk 4]
```diff
@@ -2,6 +2,9 @@
 
 ## Unreleased
 
+*Changed
```
Comment (ryanthemanuel) [inline packages/carbon-graphs/CHANGELOG.md:5]:
```suggestion
* Changed 
```

**Review by ryanthemanuel — APPROVED** [review]
Looks good with Andy's suggestions/concerns addressed

File: packages/carbon-graphs/CHANGELOG.md (hunk 4 above)
Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/CHANGELOG.md]: Fixed [here](https://github.com/cerner/terra-graphs/pull/91/commits/a5a28539c100cc564405b7aacedbe7fef5bbd226#diff-7b73f4b73c95577a16e8a58d2e1377b2204811d315c020884e80b9f22128c42aR5).

**Review by mraplumb — APPROVED** [review]

**Review by sdadn — APPROVED** [review]
