### PR TITLE
Fix: Connecting line does not go away for paired results when toggled off in IE

### LINKED ISSUE #20: Connecting line does not go away for paired results when toggled off in IE
# Bug Report

## Description
Connecting line does not go away for paired results when toggled off in IE
The line would disappear when either High or Low is toggled off in Chrome but not working as expected in IE

### Graphs affected

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [ ]  Line graph
* [x]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

## Steps to Reproduce
1. Open paired results.
2. Toggle off either High or Low legend.
3. The connecting line does not disappear.

## Additional Context / Screenshots
Carbon

## Expected Behavior
The connecting line should disappear when either High or Low legend is toggled off.

## Environment

* Component Name and Version:
* Browser Name and Version: Internet Explorer 11
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by AshishMotanamGurunadham**
### Summary
1. Made changes in order to make terra-graphs work in Internet Explorer.
2. The connecting line does not go away for paired results when toggled off in IE. The line would disappear when either High or Low is toggled off in Chrome but not working as expected in IE. Changes made accordingly in this PR to fix the above issue.

Closes #20 

### Deployment Link

https://terra-graphs-deployed-pr-#.herokuapp.com/

### Screenshots

**Terra-Graphs in Internet Explorer.**

**Before**

image

**After**

image

**Paired result graph in Internet Explorer when high is toggled:**

**Before:**

image

**After:**

image

Thank you for contributing to Terra.
@cerner/terra
@cerner/carbon

### CODE REVIEW

File: packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js [hunk 1]
```diff
@@ -683,7 +683,7 @@ const clickHandler = (graphContext, control, config, canvasSVG) => (
   const pairedBoxGroup = d3.selectAll(`.${styles.pairedBoxGroup}`);
   pairedBoxGroup.each(function () {
     const clipPath = d3.select(this).attr('clip-path');
-    if (clipPath === pairedBoxGroupClipPath) {
+    if (clipPath.replace(/['"]+/g, '') === pairedBoxGroupClipPath) {
```
Comment (sdadn) [inline packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js:686]: Shouldn't the regex statement be inside a string?

File: packages/carbon-graphs/webpack/dev-server.js [hunk 2]
```diff
@@ -29,7 +29,7 @@ const compiler = webpack({
         test: /\.(js|jsx)$/,
         include: [
           path.join(__dirname, '../', 'src'),
-          path.join(__dirname, '../','../','../', 'dev'),
+          path.join(__dirname, '../', 'dev'),
```
Comment (Veera81) [inline packages/carbon-graphs/webpack/dev-server.js:32]: Does this fix the loading dev site in IE?

File: packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js (hunk 1 above)
Comment (Veera81) [inline packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js:686]: Does this fix the pair results issue? Can you add a comment about why we are doing it this way?

File: packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js [hunk 3]
```diff
@@ -683,7 +683,7 @@ const clickHandler = (graphContext, control, config, canvasSVG) => (
   const pairedBoxGroup = d3.selectAll(`.${styles.pairedBoxGroup}`);
   pairedBoxGroup.each(function () {
     const clipPath = d3.select(this).attr('clip-path');
-    if (clipPath === pairedBoxGroupClipPath) {
```
Comment (Veera81) [inline packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js:686]: No unit tests?

**Review by Veera81 — CHANGES_REQUESTED** [review]

File: packages/carbon-graphs/webpack/dev-server.js (hunk 2 above)
Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/webpack/dev-server.js:32]: Yes veera.

File: packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js (hunk 3 above)
Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js:686]: No veera. There were already some unit tests to check those lines during the toggle.

File: packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js (hunk 1 above)
Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js:688]: yes veera and comment added [here](https://github.com/cerner/terra-graphs/pull/30/commits/591d01d03d810df52c8b3f21060fec87d4cc81c3#diff-d04c4cf6f73329ea29bf2a081e4f7b5d5ddf52580b58d6ce58bf9c7b2728fb1eR686).

**Review by sdadn — APPROVED** [review]

File: packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js (hunk 3 above)
Comment (mraplumb) [reply packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js:686]: Even though there are lines to verify this logic, it likely does not test it with the presence of the quotes.  Can we add a test that mocks the clip-path returning a value with the quotes as seen in IE so that we have a test which covers both values which we know might be returned by browsers?

Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js:686]: Added [here](https://github.com/cerner/terra-graphs/pull/30/commits/1ed69c43bc33aa00c4da32091e67acc55bfa3e66#diff-a1e1e5d218ab7da13636fbc6cce4a15cee9ab2948153df45ae61604bbeafd4afR2313).

**Review by mraplumb — APPROVED** [review]

**Review by Veera81 — APPROVED** [review]

**Review by jeremyfuksa — APPROVED** [review]
