### PR TITLE
Fixed isolation of different graph instances in same page.

### LINKED ISSUE #98: Carbon features on different instances is not being isolated.
# Bug Report

## Description
We have discovered that two Gantt instances in the same page are not fully isolated as they should be.
This leads to strange effects such as collapsing sections of the first Gantt causes data on the second Gantt to also be removed.

### Graphs affected

* [ ]  Bar graph
* [ ]  Bubble graph
* [x]  Gantt chart
* [ ]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

## Possible Solution
In the investigation we found that [dateClipPathId](https://github.com/cerner/terra-graphs/blob/main/packages/carbon-graphs/src/js/controls/Gantt/GanttConfig.js#L182) is same for both instances.  The id is same because the date is mocked and same for both Gantt instances.  
Attaching unique id to [generateDatelineClipPathId ](https://github.com/cerner/terra-graphs/blob/main/packages/carbon-graphs/src/js/core/BaseConfig/helper.js#L68) and [generateClipPathId](https://github.com/cerner/terra-graphs/blob/main/packages/carbon-graphs/src/js/core/BaseConfig/helper.js#L60) should resolve the issue.

### PR DESCRIPTION
**Pull request by AshishMotanamGurunadham**
### Summary

- Two Gantt instances on the same page are not fully isolated as they should be. This leads to strange effects such as collapsing sections of the first Gantt causes data on the second Gantt to be removed. 
- Fixed this by adding unique id to clippath.

Closes #98 

### Deployment Link

https://terra-graphs-deployed-pr-#.herokuapp.com/

Thank you for contributing to Terra.
@cerner/terra
@cerner/carbon

### CODE REVIEW

File: packages/carbon-graphs/src/js/core/BaseConfig/helper.js [hunk 1]
```diff
@@ -1,10 +1,16 @@
...
 import * as d3 from 'd3';
+import uuidv4 from 'uuid/v4';
 import { AXIS_TYPE, LINE_TYPE } from '../../helpers/constants';
 import errors from '../../helpers/errors';
 import utils from '../../helpers/utils';
 
+/**
+ * Creates random ID
+ */
+const idRef = () => uuidv4();
```
Comment (yuderekyu) [inline packages/carbon-graphs/src/js/core/BaseConfig/helper.js:12]: imo there's no benefit with abstracting the `uuidv4` function within another function, because we are not doing any extra logic. i think it's much clearer to directly use the `uuidv4` function instead - thoughts?

File: packages/carbon-graphs/src/js/core/BaseConfig/helper.js [hunk 2]
```diff
@@ -57,15 +63,15 @@ export const getType = (type) => getDefaultValue(type, AXIS_TYPE.DEFAULT);
...
+export const generateClipPathId = () => `carbon-${+new Date()}-${idRef()}-clip`;
 
 /**
  * Generates a clip path ID for Dateline based on current date
  *
  * @private
  * @returns {string} Clip path Dateline ID
  */
-export const generateDatelineClipPathId = () => `carbon-${+new Date()}-dateline-clip`;
+export const generateDatelineClipPathId = () => `carbon-${+new Date()}-${idRef()}-dateline-clip`;
```
Comment (yuderekyu) [inline packages/carbon-graphs/src/js/core/BaseConfig/helper.js:74]: hmmmm, just curious, what exactly is this fixing? at a glance, it looks like the ids are already unique: `-clip` vs `dateline-clip`. is there a collision outside of these two ids?

Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/src/js/core/BaseConfig/helper.js:74]: Well, id is unique in all the cases but one of our consumers is mocking the date which results in different graphs creating the same id. So taking that case into consideration we have to add extra unique things to make ID unique.

Comment (yuderekyu) [reply packages/carbon-graphs/src/js/core/BaseConfig/helper.js:74]: but wouldn't the ids still be unique in that case? `${mock date}-clip` !== `${mock date}-dateline-clip`. not trying to be a stickler, just trying to understand the bug.

i agree that uuids should be used to we can guarantee that ids are unique when someone renders multiple graphs.

Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/src/js/core/BaseConfig/helper.js:74]: When we generate two graphs in same page 1st graph will graph will have ${mock date}-clip !== ${mock date}-dateline-clip and second graph will also consists of ${mock date}-clip !== ${mock date}-dateline-clip. In that case, when we try to remove content from the first graph the content from the second graph also gets deleted since they both consist of the same id. And Yes we can remove the date.

**Note**: Problem exists when there are two graphs in same page.

File: packages/carbon-graphs/src/js/core/BaseConfig/helper.js (hunk 1 above)
Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/src/js/core/BaseConfig/helper.js]: Fixed [here](https://github.com/cerner/terra-graphs/pull/117/commits/fccb8fb24d10df112091db185401cc0916207485#diff-606396e5aa13b62e41638acfeb1622b804a2c42a86dcf491ae3c52c60fd49389R61).

File: packages/carbon-graphs/src/js/core/BaseConfig/helper.js (hunk 2 above)
Comment (AshishMotanamGurunadham) [reply packages/carbon-graphs/src/js/core/BaseConfig/helper.js]: Removed date from clip-path id [here](https://github.com/cerner/terra-graphs/pull/117/commits/316365904951708854fec20afc1a374298693967#diff-606396e5aa13b62e41638acfeb1622b804a2c42a86dcf491ae3c52c60fd49389L66).

**Review by yuderekyu — COMMENTED** [review]
are there unit tests for these functions?

**Comment by AshishMotanamGurunadham** [comment]
> are there unit tests for these functions?

Since it is just id correction, haven't written any unit tests.

File: package.json [hunk 3]
```diff
@@ -98,6 +98,7 @@
     "terra-enzyme-intl": "^3.0.0",
     "terra-toolkit": "^6.2.0",
     "url-loader": "^4.1.1",
+    "uuidv4": "^3.0.0",
```
Comment (sdadn) [inline package.json:101]: The documentation says that `uuidv4` will be deprecated in the future and to use https://www.npmjs.com/package/uuid instead. Can you make this change?

Comment (AshishMotanamGurunadham) [reply package.json]: Fixed [here](https://github.com/cerner/terra-graphs/pull/117/commits/382664c0f4a6e411b79d006acf424f7431e5e7cd#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R101).

**Comment by yuderekyu** [comment]
> > are there unit tests for these functions?
> 
> Since it is just id correction, haven't written any unit tests.

imo we should verify that these functions generate the expected ids, and call the uuid library. I think that's especially important if these didn't have tests before, and we're changing the logic.

File: package.json [hunk 4]
```diff
@@ -98,6 +98,7 @@
     "terra-enzyme-intl": "^3.0.0",
     "terra-toolkit": "^6.2.0",
     "url-loader": "^4.1.1",
+    "uuid": "^8.3.2",
```
Comment (ryanthemanuel) [inline package.json:101]: Unfortunately, I think we need to use v3 like we do in terra-application: https://github.com/cerner/terra-application/blob/main/package.json#L127

v8 isn't compatible with IE10 which is needed for MPages.

Comment (AshishMotanamGurunadham) [reply package.json]: Removed the commit.

**Comment by AshishMotanamGurunadham** [comment]
> > > are there unit tests for these functions?
> > 
> > 
> > Since it is just id correction, haven't written any unit tests.
> 
> imo we should verify that these functions generate the expected ids, and call the uuid library. I think that's especially important if these didn't have tests before, and we're changing the logic.

Added unit test case [here](https://github.com/cerner/terra-graphs/pull/117/files#diff-bf8cb9d6ee75a2a47b760839f763f9ac5c966aa102feee14ca4a9c854e402b1fR399).

**Review by ryanthemanuel — APPROVED** [review]
