### PR TITLE
Fix: Resize Handler Console Error Fix (fixes #10)

### LINKED ISSUE #10: Console error while using resizeHandler
**What part of Carbon does this bug correlate to?**
General graph logic:

* [x]  Graph attributes (axes, legends, regions...etc.)
* [ ]  Other (please specify): 

Specific graph logic:

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [x]  Line graph
* [x]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

**Describe the bug**
There is a console error in our advanced-graphing application when we use resizeHandler().

**Expected behavior**
Graphs should be resized without any console error in the browser.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by JananiGunasekaran**
### Summary

Using resizeHandler in advanced graphing application throws a console error. 
image
To fix the error, we have to add a condition to check if the graphContainer is present and then resize the graph.

Closes #10 

### Deployment Link

https://terra-graphs-deployed-pr-#.herokuapp.com/

### Testing

Unit test

### Additional Details

Thank you for contributing to Terra.
@cerner/terra
@cerner/carbon

### CODE REVIEW

File: packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js [hunk 1]
```diff
@@ -586,4 +586,27 @@ describe('Graph - Resize', () => {
       expect(graph.config.canvasHeight).toBe(250);
     });
   });
+  describe("Only when graph container is present", () => {
```
Comment (Veera81) [inline packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js:589]: nit: `when the graph container is present`

File: packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js [hunk 2]
```diff
@@ -586,4 +586,27 @@ describe('Graph - Resize', () => {
...
+    it("Resize the graph", (done) => {
```
Comment (Veera81) [inline packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js:590]: nit: `should resize the graph`

File: packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js (hunk 1 above)
Comment (Veera81) [inline packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js:589]: Can we add another test for `when the graph container is not present`?

File: packages/carbon-graphs/CHANGELOG.md [hunk 3]
```diff
@@ -1,5 +1,8 @@
 # ChangeLog
 
+* Changed
+  * Added a condition to check if graphContainer is present and then resize the graph.
```
Comment (Veera81) [inline packages/carbon-graphs/CHANGELOG.md:4]: Should it move to the below Unreleased section?

**Review by Veera81 — CHANGES_REQUESTED** [review]

File: packages/carbon-graphs/CHANGELOG.md (hunk 3 above)
Comment (JananiGunasekaran) [reply packages/carbon-graphs/CHANGELOG.md:4]: I saw Pranav's PR and added it in the same place. Please let me know if it should be moved.

File: packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js (hunk 1 above)
Comment (JananiGunasekaran) [reply packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js]: Updated [here](https://github.com/JananiGunasekaran/terra-graphs/commit/b4b9e470b74001a11534a3d7d492a2c1f10c8d52).

File: packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js (hunk 2 above)
Comment (JananiGunasekaran) [reply packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js]: Updated [here](https://github.com/JananiGunasekaran/terra-graphs/commit/b4b9e470b74001a11534a3d7d492a2c1f10c8d52).

File: packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js (hunk 1 above)
Comment (JananiGunasekaran) [reply packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js]: When the graph container is not present, we are restricting from executing the statements which set the canvas width, scale the graph and translate the graph. A unit test to check if those statements are not getting executed was not possible, thats the reason I wrote an unit test to check if the statements are being executed if the graph container is actually present.

**Comment by JananiGunasekaran** [comment]
I have addressed all the comments. Please review.

File: packages/carbon-graphs/CHANGELOG.md (hunk 3 above)
Comment (Veera81) [reply packages/carbon-graphs/CHANGELOG.md:4]: I saw one of Pranav's PR. It was added below the Unreleased section. Correct me if I'm wrong

image

https://github.com/cerner/terra-graphs/pull/18/files?short_path=7b73f4b#diff-7b73f4b73c95577a16e8a58d2e1377b2204811d315c020884e80b9f22128c42a

**Review by Veera81 — APPROVED** [review]

**Review by AshishMotanamGurunadham — APPROVED** [review]

File: packages/carbon-graphs/CHANGELOG.md (hunk 3 above)
Comment (sdadn) [reply packages/carbon-graphs/CHANGELOG.md:4]: Yes, I would say it needs to be in the unreleased section as well since we're no longer releasing after every PR.

Comment (sdadn) [reply packages/carbon-graphs/CHANGELOG.md:4]: I would also move it to below `Migrated to the terra-graphs mono-rep.` so that this is in chronological order.

Comment (JananiGunasekaran) [reply packages/carbon-graphs/CHANGELOG.md]: I have updated it [here](https://github.com/JananiGunasekaran/terra-graphs/commit/510ef795df968f9d5b6f4ea8393ac2e2e17cfe1e).

**Review by sdadn — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

**Comment by JananiGunasekaran** [comment]
@Veera81 Are we good to merge this PR?
